# Generated by Django 5.0.8 on 2024-08-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=8000)),
                ('node_type', models.CharField(choices=[('master', 'Master'), ('local', 'Local'), ('self', 'Self'), ('remote', 'Remote')], default='remote', max_length=10)),
                ('trust', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=0)),
                ('last_online', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
