# Generated by Django 5.0.8 on 2024-08-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NodeModel',
            new_name='Node',
        ),
    ]
