# Generated by Django 5.0.8 on 2024-08-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_rename_nodemodel_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='last_online',
            new_name='last_seen',
        ),
    ]
